### ISSUE TITLE
详细配置一键展开 

### ISSUE THREAD

**Issue by Sun-0928** [LeavesMC/Documentation#2]
- [x] 文档一键全部展开这个功能（像老文档那样
![IMG_20240316_231858](https://github.com/LeavesMC/Documentation/assets/137071925/564ee239-9247-460f-b2c0-ff0360cc0c54)

**Comment by Bluemangoo** [comment]
6

**Comment by MC-XiaoHei** [comment]
> 6

怎么了（

**Comment by Bluemangoo** [comment]
> > 6
> 
> 怎么了（

assigned and unassigned

**Comment by MC-XiaoHei** [comment]
简单实现了一下功能，美化交给芒果吧。@Bluemangoo

**Comment by Bluemangoo** [comment]
@MC-XiaoHei 你别直接交上去啊，开个新分支开个pr，main那个reset掉。

**Comment by MC-XiaoHei** [comment]
帮帮我.webp 我在学校

**Comment by Bluemangoo** [comment]
> 帮帮我.webp 我在学校

我也在（

codespace
