### ISSUE TITLE
[Missing] 关闭fill set产生的方块更新

### ISSUE THREAD

**Issue by Monoryxiaole** [LeavesMC/Documentation#23]
### What type of documentation are we missing?

Project

### What should be added?

`/leaves` 命令

- [ ]  关闭fill方块更新
- [ ]  关闭set方块更新
- [ ]  关闭全局方块更新

**Comment by LittleChest** [comment]
甚至把tasks都写好了（

**Comment by LittleChest** [comment]
此存储库为 LeavesMC 文档站，不接受 Leaves 核心的功能请求，请转到 LeavesMC/Leaves

**Comment by LittleChest** [comment]
Duplicate of #10
