### ISSUE TITLE
为配置随机项增添额外style

### ISSUE THREAD

**Issue by Bluemangoo** [LeavesMC/Documentation#4]
给那个值换个颜色或在哪里加个标志标记它的随机项。

**Comment by Bluemangoo** [comment]
我没挑好颜色， @LittleChest 你挑一个。在 random-color 分支。

**Comment by Bluemangoo** [comment]
或者加个svg的角标也行。

**Comment by LittleChest** [comment]
值颜色随机 这样提示够明显的了（

红和黄比较好 这两个来回切 剩下的都会和现有颜色冲突

**Comment by Bluemangoo** [comment]
红色带点警示感觉，之前有个金色来着，稍微有点点突兀。

考虑svg的右上角星号。（svg是防止被选中复制

**Comment by LittleChest** [comment]
> 红色带点警示感觉，之前有个金色来着，稍微有点点突兀。
> 
> 考虑svg的右上角星号。（svg是防止被选中复制

有人会手动把*打上 还是换色比较好

**Comment by LittleChest** [comment]
Move to #5

**Comment by Bluemangoo** [comment]
？一个issue对应一个pr是基本操作。

而且pr link了这个issue，pr合并会自动close的。

**Comment by LittleChest** [comment]
> ？一个issue对应一个pr是基本操作。
> 
> 而且pr link了这个issue，pr合并会自动close的。

pr本身也可以commit 这个操作一般是issue和pr不是同一个人发起的情况
一个人发起为什么要占两个）
